### PR TITLE
Remove SmoothSphereHalfSpaceForce from Moco.

### PR DESCRIPTION
**Pull request by chrisdembia**
### Brief summary of changes

SmoothSphereHalfSpaceForce is now in `opensim-core`; this PR removes this class from Moco.

### CHANGELOG.md (choose one)

- [x] updated

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-moco/608)

### CODE REVIEW

**Comment by carmichaelong** [comment]
It's cool that the contact is now directly in opensim-core! I left one comment, and have just one other note:

While comparing example2Dwalking.m with the one on master, I noticed that the optional GRF tracking is gone from this version but didn't show up in the diff. Is this intentional?

**Comment by chrisdembia** [comment]
___
*[Moco/Bindings/Java/Matlab/Examples/example2DWalking/example2DWalking.m, line 200 at r1](https://reviewable.io/reviews/opensim-org/opensim-moco/608#-M3b7Gu97K1IDNWQyF-Q:-M3bHuoTAHi5UhjZhCr6:b7s8ech) ([raw file](https://github.com/opensim-org/opensim-moco/blob/8f8677cc0d356c3b773d3a9c4a49be9a4b5cd08f/Moco/Bindings/Java/Matlab/Examples/example2DWalking/example2DWalking.m#L200)):*
<details><summary><i>Previously, chrisdembia (Christopher Dembia) wrote…</i></summary><blockquote>

Thanks for catching this! Done.
</blockquote></details>

(oops; I didn't push the code yet)

**Comment by chrisdembia** [comment]
Thanks @carmichaelong . You're up, @nickbianco !

**Comment by chrisdembia** [comment]
@nickbianco I think we should include this change for the Moco paper. I'm happy to update the models in the `mocopaper` repository once this is merged.

**Comment by chrisdembia** [comment]
Thanks; I'll merge this after we send our draft to Jen.

**Pull request merged**
