### PR TITLE
Add smooth Bhargava2004 metabolics model

### PR DESCRIPTION
**Pull request by antoinefalisse**
Fixes issue #450 

### Brief summary of changes
The PR adds a Bhargava2004Metabolics calculator component. The model is smooth - if statements were replaced by tanh approximations. The PR integrates changes from  #479, i.e. the Minetti-Alexander metabolics model but also the MocoOutputGoal. This is WIP, I think we still need to make design choices before cleaning and commenting everything. 

Issue #450 suggests fixing the probes rather than rewriting the model, so maybe you do not want such model. Don't hesitate to let me know.

Thanks in advance for your feedback.

### Details (optional)
I am still having an issue at this stage. When trying to run `example2Dwalking`, I receive this error message:
```
Socket 'muscle' not connected.
        In Object 'hamstrings_r' of type SmoothBhargava2004Metabolics_MuscleParameters.
        Thrown at Component.h:905 in getConnectee().
```

I am not sure where the issue comes from, since I have `connectSocket_muscle()` commands in the constructors. I wonder if I miss methods in `SmoothBhargava2004Metabolics_MuscleParameters` (should there be something like `extendAdd...`?) or if I forget things when defining `metabolics` in `example2Dwalking` (should there be a `finalizeConnections()` or something like that?).

I have added an option `get_use_fiber_length_dependence_on_maintenance_rate`. When true (default), the model relies on a piecewise linear function (as described in the publication). Yet I am not sure this function is twice differentiable, and, if so, it is probably not very suited for gradient-based optimization. In my simulations, I did not use such function and, instead, used normalized fiber length directly. I am not sure this is great but I don't think it has a large impact either. I am fine with removing this addition, but it would be interesting to first test in simulations (when the model works fine).

### CHANGELOG.md (choose one)

- [ ] updated
- [ ] no need to update because...

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-moco/532)

### CODE REVIEW

**Comment by antoinefalisse** [comment]
@chrisdembia and @nickbianco, sorry for the delay about this. I will try to dedicate some time to moco in the coming week. I cannot remember what your suggestions were to deal with the issue I mention above (`Socket 'muscle' not connected...`). Any ideas before I dive into that? Thanks.

**Comment by chrisdembia** [comment]
I don't remember having any insight into that error.

Unfortunately, I will have limited bandwidth to review this PR for the next 2 months.

**Comment by chrisdembia** [comment]
I haven't reviewed this yet but I resolved merged conflicts.

**Comment by antoinefalisse** [comment]
Thanks for your responses.

> 
> 
> I think you do need to call `finalizeConnections()` after each `connectSocket_muscle()`call in the constructors.

Can you explain me:

- why in [the contact model](https://github.com/opensim-org/opensim-moco/blob/master/Moco/Moco/Components/SmoothSphereHalfSpaceForce.cpp#L47), there was no need to use `finalizeConnections()`?

- how to actually use `finalizeConnections()` in my case? I first thought that adding something like `finalizeConnections(muscle)`[here](https://github.com/opensim-org/opensim-moco/blob/bhargava_smooth/Moco/Moco/Components/SmoothBhargava2004Metabolics.cpp#L46) would work but there is an issue cause `muscle` is `const`. If I drop the `const`, then it becomes an issue when trying to access a muscle when setting up the problem (e.g., `baseModel.getComponent<Muscle>("hamstrings_r")` returns a `const`). Where am I wrong there?

- if there is a need to have something like `extendFinalizeConnections()`?

Thanks a lot.

**Comment by nickbianco** [comment]
I just noticed there's a missing `Super::extendAddToSystem(system)` call in your component's `extendAddToSystem()`. That might be part of the problem.

**Comment by antoinefalisse** [comment]
Thanks @nickbianco, I think I was also missing a `Super::extendConnectToModel(model);` in `extendConnectToModel()`. It did not solve the issue yet though.

**Comment by nickbianco** [comment]
@chrisdembia and I have been chatting, and we think the issue is happening during the `metabolics->addMuscle(muscle_parameters)` calls. Even the each parameter is set by `std::move()` in these calls, we think the socket connectees might be getting cleared (which happens whenever a copy is made). 

A way to avoid this would be to have `addMuscle()` take all the arguments needed for each `SmoothBhargava2004Metabolics_MuscleParameter`, and construct them inside of `addMuscle()`. Users would only have to deal with the main `SmoothBhargava2004Metabolics` that way too.

**Comment by antoinefalisse** [comment]
Are you suggesting something like [this](https://github.com/opensim-org/opensim-moco/blob/bhargava_smooth/Moco/Moco/Components/SmoothBhargava2004Metabolics.h#L178)? Still the same error.

**Comment by chrisdembia** [comment]
That's one step closer. Construct an empty Parameters object, append it, then set all the properties of it (you'll have to fetch out the last object added).


```cpp
append_muscle_parameters(SmoothBhargava2004Metabolics_MuscleParameters());
auto& mp = get_muscle_parameters(getProperty_muscle_parameters().size() - 1);
mp.set_...();
mp.connectSocket_muscle(...);
```

**Comment by antoinefalisse** [comment]
Thanks. Not there yet though...[(see adjusted code)](https://github.com/opensim-org/opensim-moco/blob/bhargava_smooth/Moco/Moco/Components/SmoothBhargava2004Metabolics.h#L188)

**Comment by antoinefalisse** [comment]
The tracking problem as it is set up now converges in 241 iterations and the tracking motion looks great. Increasing the weight of the metabolic term from 0.1 to 1 or higher gives bad results though (the model is not even walking anymore). The breakdown of the objective (that's a cool feature) gives me 0.16 for the metabolic term so the COT is about 1.6 J / kg / m for half a gait cycle I think. (**It would be nice to be able to extract the COT from the solution**). So about 3.2 J / kg / m for a full gait cycle. It is low but it is a 2D model so the parameters (e.g., specific tensions) might not be very appropriate + I do not know if we should care too much about the realism of the solution at this stage. I am glad that it seems to work.

**Comment by antoinefalisse** [comment]
@chrisdembia, building the dependencies on Mac is failing. Anything I should be aware of?

**Comment by chrisdembia** [comment]
> @chrisdembia, building the dependencies on Mac is failing. Anything I should be aware of?

Thanks for bringing this to my attention. Looks like the ADOL-C repository moved to GitHub. I created an issue for this: https://github.com/opensim-org/opensim-moco/issues/602

**Comment by antoinefalisse** [comment]
@nickbianco, thanks for the feedback and sorry for the delay. I should have time to work on that next week.

**Comment by antoinefalisse** [comment]
@chrisdembia and @nickbianco, where should I move the example with the metabolics model? I think we discussed at some point that it would be good to have it separate from the main 2D walking example. Can't recall where we said we should move it. Thanks.

**Comment by antoinefalisse** [comment]
Thanks, it is done now. I think another feature that would be quite nice is an easy way to retrieve the metabolic power from the solution and to be able to normalize it by model mass and distance traveled to have the COT. How would you go about that? FYI, the problem converged in 12min.

**Comment by chrisdembia** [comment]
The clamped function is linear, right? So you might be able to adapt the Huber function to directly model the clamped function.

**Comment by nickbianco** [comment]
I was curious to how this Huber function would work, so I wrote a quick Matlab function that helped me visualize it. I think the `clamp_func` below could be substituted in for the existing conditional function whenever clamping is needed. 

@antoinefalisse I could give it a try if you'd like. But also feel free to use this as a jumping off point for yourself.

```matlab
function huber

% dummy variable for muscle state
state = -1:0.0001:1;

% unclamped heat rate function
% use the slope to fine tune the transition region (must rescale y-axis after)
slope = 2; 
% this shift is necessary for the clamped and unclamped curves to line up
shift = 0.5*(1/slope);
totalHeatRate = @(x) slope*x;

% Compute and plot clamped and unclamped curves
totalHeatRate_unclamped = zeros(length(state), 1);
totalHeatRate_clamped = zeros(length(state), 1);
for i = 1:length(state)
    totalHeatRate_unclamped(i) = totalHeatRate(state(i));
    % Note the use of the shift here
    totalHeatRate_clamped(i) = clamp_func(state(i) + shift, totalHeatRate);
end

plot(state, totalHeatRate_unclamped)
hold on
plot(state, totalHeatRate_clamped)

end

% See first equation in https://en.wikipedia.org/wiki/Huber_loss
% Here, delta = 1, a = state, and we add a third condition in the if-else block
% since the function should be one-sided.
function f = clamp_func(state, unclamped_func)

if unclamped_func(state) < 0
    f = 0;
elseif unclamped_func(state) <= 1
    f = 0.5*unclamped_func(state)^2;
else
    f = unclamped_func(state) - 0.5;
end

end
```

**Comment by chrisdembia** [comment]
I've dismissed my review. Go ahead, @antoinefalisse :)

**Comment by antoinefalisse** [comment]
Awesome, glad to have that done! Hope it will be useful for users!
I don't have the rights to merge so feel free to go ahead, no problem :)
Thanks for your patience with this work, great feedback as always!

Ps: Umberger2003 now? ;)

**Comment by chrisdembia** [comment]
> Ps: Umberger2003 now? ;)

Yeah! :)

**Pull request merged**
