### PR TITLE
Minimum distance constraint

### PR DESCRIPTION
**Pull request by nickbianco**
### Brief summary of changes
Add `MocoMinimumDistanceConstraint`, a path constraint class that requires that the origin of pairs of model frames must be a specified minimum distance apart.

### CHANGELOG.md (choose one)

- [x] updated
- [ ] no need to update because...

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-moco/529)

### CODE REVIEW

**Comment by chrisdembia** [comment]
Can you change the target to `master`? After it's merged, we can merge `master` into `preprint`.

**Comment by chrisdembia** [comment]
@nickbianco I created a `paper` branch off of this one, and I think we can replace `preprint` with `paper` as the branch that we use with the `mocopaper` repo. And then we can be a little sloppier with the `paper` branch.

**Comment by chrisdembia** [comment]
This PR has a bunch of leftovers from the preprint branch.

**Comment by nickbianco** [comment]
@chrisdembia I cleaned this PR, removing all preprint leftovers not necessary to it. Ready to review.

**Comment by chrisdembia** [comment]
Merge Conflict

**Comment by chrisdembia** [comment]
Feel free to merge when tests pass.

**Comment by nickbianco** [comment]
Thanks @chrisdembia!

**Pull request merged**
