### PR TITLE
Add acceleration and angular velocity tracking goals

### PR DESCRIPTION
**Pull request by nickbianco**
### Brief summary of changes
- Adds `MocoAccelerationTrackingGoal` and `MocoAngularVelocityTrackingGoal` in anticipation of supporting tracking IMU data.
- Tests added similar to the orientation and translation tracking goals.
- Other various minor updates.

### Details (optional)
Additional changes will be necessary to fully support IMU tracking. Specifically, how errors are computed for `MocoAccelerationTrackingGoal` will need to be updated to account for body-fixed IMU accelerations and the gravitational acceleration offset.

### CHANGELOG.md (choose one)

- [x] updated
- [ ] no need to update because...

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-moco/513)

### CODE REVIEW

**Comment by chrisdembia** [comment]
@jenhicks @jimmyDunne @aymanhab @malborno, you all might be interested in this.

**Comment by chrisdembia** [comment]
@nickbianco 

```
/Users/runner/runners/2.160.2/work/opensim-moco/opensim-moco/Moco/Moco/MocoGoal/MocoTranslationTrackingGoal.cpp:165:23: error: comparison of integers of different signs: 'int' and 'std::__1::vector<std::__1::basic_string<char>, std::__1::allocator<std::__1::basic_string<char> > >::size_type' (aka 'unsigned long') [-Werror,-Wsign-compare]
83
    for (int i = 0; i < m_frame_paths.size(); i++) {
84
                    ~ ^ ~~~~~~~~~~~~~~~~~~~~
85
[ 32%] Building CXX object Moco/Moco/CMakeFiles/osimMoco.dir/MocoGoal/MocoAccelerationTrackingGoal.cpp.o
86
/Users/runner/runners/2.160.2/work/opensim-moco/opensim-moco/Moco/Moco/MocoGoal/MocoAngularVelocityTrackingGoal.cpp:169:23: error: comparison of integers of different signs: 'int' and 'std::__1::vector<std::__1::basic_string<char>, std::__1::allocator<std::__1::basic_string<char> > >::size_type' (aka 'unsigned long') [-Werror,-Wsign-compare]
87
    for (int i = 0; i < m_frame_paths.size(); i++) {
88
                    ~ ^ ~~~~~~~~~~~~~~~~~~~~
89
1 error generated.
90
make[2]: *** [Moco/Moco/CMakeFiles/osimMoco.dir/MocoGoal/MocoTranslationTrackingGoal.cpp.o] Error 1
91
make[2]: *** Waiting for unfinished jobs....
92
/Users/runner/runners/2.160.2/work/opensim-moco/opensim-moco/Moco/Moco/MocoGoal/MocoAccelerationTrackingGoal.cpp:128:23: error: comparison of integers of different signs: 'int' and 'std::__1::vector<std::__1::basic_string<char>, std::__1::allocator<std::__1::basic_string<char> > >::size_type' (aka 'unsigned long') [-Werror,-Wsign-compare]
93
    for (int i = 0; i < m_frame_paths.size(); i++) {
94
                    ~ ^ ~~~~~~~~~~~~~~~~~~~~
```

**Comment by nickbianco** [comment]
@chrisdembia I fixed the casting to int issue. The Travis builds will still fail for CMake not finding gfortran (and quadmath I think), but you'll have to show me how to fix those.

**Comment by chrisdembia** [comment]
I don't want to hold this up because of the Travis failure, especially since Actions is working.

**Pull request merged**
