### PR TITLE
sitToStand --> squatToStand

### PR DESCRIPTION
**Pull request by nickbianco**
### Brief summary of changes
This PR updates all sitToStand examples and related files to the name "squatToStand", which has become our more recent terminology.

### CHANGELOG.md (choose one)

- [x] updated
- [ ] no need to update because...

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-moco/566)

### CODE REVIEW

**Comment by nickbianco** [comment]
@chrisdembia the Mac build is failing but I can't view the log for some reason. I tried downloading the logs and the Build Moco step (and all following steps) were not included.

**Comment by nickbianco** [comment]
The previous commit was building fine, and there's no reason why the latest commit changes would affect a build, so I restarted the CI.

**Comment by chrisdembia** [comment]
Yeah sometimes GitHub Actions doesn’t show error messages. Pretty frustrating.

**Comment by nickbianco** [comment]
Thanks @chrisdembia.

**Pull request merged**
